### PR TITLE
chore: use Thingweb bot for release preparation

### PR DESCRIPTION
**Pull request by JKRhb**
This PR will probably incorporate the solution found in https://github.com/eclipse-thingweb/.eclipsefdn/pull/21, resolving the issues currently experienced in the context of #144.

### CODE REVIEW

**Comment by netomi** [comment]
just my 2c on this topic: you should setup branch protection rules in such a way that it is supported by your development workflow and resources. If you are the sole committer to a project, requiring a number of approvals is certainly counter-productive. The main reason to setup branch protection rules is to prevent force pushes to e.g. the default branch. Requiring reviews is a good thing in general and a sign for a more mature process, however it depends on your project structure. I will leave it up to you, maybe set the number of required approvals to 0 for the start and then update as needed.

**Comment by JKRhb** [comment]
> just my 2c on this topic: you should setup branch protection rules in such a way that it is supported by your development workflow and resources. If you are the sole committer to a project, requiring a number of approvals is certainly counter-productive. The main reason to setup branch protection rules is to prevent force pushes to e.g. the default branch. Requiring reviews is a good thing in general and a sign for a more mature process, however it depends on your project structure. I will leave it up to you, maybe set the number of required approvals to 0 for the start and then update as needed.

Thank you for your feedback! I think at the moment, setting the number to of required approvals to 0 would definitely make sense, if this would also be okay for you, @relu91 & @danielpeintner.

**Comment by JKRhb** [comment]
I just opened https://github.com/eclipse-thingweb/.eclipsefdn/pull/22 for potentially updating the configuration.

**Comment by JKRhb** [comment]
Since the configuration for required approvals has been updated, I would go ahead and merge this PR to make sure that the new CI configuration works.

**Pull request merged**
