### PR TITLE
chore: update author in copyright headers

### LINKED ISSUE #67: Update author in copyright headers

### PR DESCRIPTION
**Pull request by JKRhb**
Resolves #67.

### CODE REVIEW

**Comment by JKRhb** [comment]
CC @falko17

**Review by falko17 — APPROVED** [review]

**Comment by egekorkan** [comment]
By the way, why not use 2023 everywhere?

**Comment by JKRhb** [comment]
> By the way, why not use 2023 everywhere?

I personally like to only use the first year the respective source file was created (as this way you don't need to continuously update the year). However, we could of course also use 2023 and/or use a similar strategy as in node-wot.

**Comment by danielpeintner** [comment]
I don't have a strong preference (do we need one for thingweb projects?).

Anyhow, I agree that keeping the year up-to-date is cumbersome, especially if we update the year every time changes to a file are made (as done in node-wot).
Usually I like to see both "year"s, first the year once a file has been first created and second once it was recently updated ... but that would lead to a lot of efforts that might not be worth it.

In node-wot we use a simple [Java code](https://github.com/eclipse-thingweb/node-wot/blob/master/utils/fix-copyright/CopyrightFix.java) that updates the copyrights...

**Pull request merged**
